import type {
  ActionTask,
  ExecutionLogEntry,
  IntegrationItem,
  SystemStats,
} from "./types";

export const BRAND_NAME = "LifePilot";
export const AGENT_NAME = "LifePilot Agent";
export const HACKATHON_BADGE = "AWS Strands Hackathon";

export const CATEGORIES = ["Finance", "Calendar", "Errands", "Family"] as const;

export const initialStats: SystemStats = {
  totalTasks: 148,
  timeSavedHours: 34.5,
  pendingApprovals: 3,
  activeAutomations: 6,
  autoExecuted: 121,
  autonomyThreshold: 100,
  budgetUsed: 68,
  budgetLimit: 100,
  scheduleConflicts: 1,
};

export const initialTasks: ActionTask[] = [
  {
    id: "t-1001",
    title: "Utility bill spike",
    description:
      "City Water Co. bill is $145, exceeding your $100 auto-pay threshold. Agent paused action pending approval.",
    category: "Finance",
    status: "pending",
    impact: 145,
    currency: "USD",
    requiresApproval: true,
    reason: "Exceeds auto-payment threshold ($145 > $100).",
    timestamp: Date.now() - 1000 * 60 * 4,
    executionMs: 42,
    provider: "City Water Co.",
    payload: {
      amount: 145,
      threshold: 100,
      due: "2026-06-02",
      account: "••• 4412",
    },
  },
  {
    id: "t-1002",
    title: "Dentist double-booking conflict",
    description:
      "Routine cleaning on Jun 14 clashes with quarterly tax appointment. Agent proposes rescheduling to Jun 16.",
    category: "Calendar",
    status: "pending",
    impact: 0,
    requiresApproval: true,
    reason: "Schedule conflict detected across 2 calendars.",
    timestamp: Date.now() - 1000 * 60 * 18,
    executionMs: 76,
    provider: "Google Calendar",
    payload: {
      original: "Jun 14, 10:30 AM",
      proposed: "Jun 16, 2:00 PM",
      axes: ["Cleaning", "Tax appointment"],
    },
  },
  {
    id: "t-1003",
    title: "Weekly grocery reorder price increase",
    description:
      "Recurring Instacart order rose by $18 due to supplier change. Agent proposes switching to an equivalent cheaper basket.",
    category: "Errands",
    status: "pending",
    impact: 18,
    currency: "USD",
    requiresApproval: true,
    reason: "Recurring order cost variance exceeds 10%.",
    timestamp: Date.now() - 1000 * 60 * 42,
    executionMs: 51,
    provider: "Instacart",
    payload: {
      delta: "+$18",
      deltaPct: "+12.4%",
      items: 9,
      newTotal: 162,
    },
  },
  {
    id: "t-9001",
    title: "Gym subscription auto-paid",
    description: "Monthly gym membership renewed within autonomous budget.",
    category: "Finance",
    status: "executed",
    impact: 35,
    currency: "USD",
    requiresApproval: false,
    timestamp: Date.now() - 1000 * 60 * 6,
    executionMs: 24,
    provider: "Chase Bank",
    payload: { amount: 35, plan: "Member Plus", auto: true },
  },
];

export const initialLogs: ExecutionLogEntry[] = [
  {
    id: "log-1",
    taskId: "t-9001",
    title: "Auto-paid gym subscription",
    category: "Finance",
    severity: "auto",
    timestamp: Date.now() - 1000 * 60 * 6,
    latencyMs: 242,
    model: "claude-haiku",
    trace: [
      { step: "Scan invoice", detail: "Found monthly debit of $35", latencyMs: 64 },
      { step: "Check budget", detail: "$35 < $100 autonomy limit", latencyMs: 40 },
      { step: "Authorize", detail: "Auto-executed under threshold", latencyMs: 30 },
      { step: "Settle", detail: "Paid via Chase debit ••• 4412", latencyMs: 108 },
    ],
    payload: { amount: 35, channel: "Chase" },
  },
  {
    id: "log-2",
    taskId: "t-1001",
    title: "Utility bill spike flagged",
    category: "Finance",
    severity: "escalated",
    timestamp: Date.now() - 1000 * 60 * 4,
    latencyMs: 310,
    model: "claude-sonnet",
    trace: [
      { step: "Fetch invoice", detail: "City Water Co. bill $145", latencyMs: 90 },
      { step: "Compare threshold", detail: "Exceeds $100 auto-pay limit", latencyMs: 46 },
      { step: "Escalate", detail: "Queued for approval", latencyMs: 52 },
      { step: "Notify", detail: "Pushed decision request to user", latencyMs: 122 },
    ],
    payload: { amount: 145, threshold: 100 },
  },
  {
    id: "log-3",
    taskId: "t-9002",
    title: "Synced flight delays to calendar",
    category: "Calendar",
    severity: "auto",
    timestamp: Date.now() - 1000 * 60 * 26,
    latencyMs: 180,
    model: "claude-haiku",
    trace: [
      { step: "Detect gate change", detail: "AA1142 delayed 40 min", latencyMs: 72 },
      { step: "Update calendar", detail: "Inserted revised arrival", latencyMs: 48 },
      { step: "Recompute buffer", detail: "Padding recalculated", latencyMs: 60 },
    ],
    payload: { flight: "AA1142", delay: "40m" },
  },
  {
    id: "log-4",
    taskId: "t-9003",
    title: "Dispatched robot vacuum",
    category: "Errands",
    severity: "auto",
    timestamp: Date.now() - 1000 * 60 * 52,
    latencyMs: 96,
    model: "claude-haiku",
    trace: [
      { step: "Runtime check", detail: "Home schedule: clean at 9 AM", latencyMs: 34 },
      { step: "Dispatch", detail: "Roborock started zone A", latencyMs: 62 },
    ],
    payload: { device: "Roborock S8", zone: "A" },
  },
  {
    id: "log-5",
    taskId: "t-9004",
    title: "Optimized electricity plan",
    category: "Finance",
    severity: "resolved",
    timestamp: Date.now() - 1000 * 60 * 78,
    latencyMs: 540,
    model: "claude-sonnet",
    trace: [
      { step: "Audit usage", detail: "Analyzed 90 days of usage", latencyMs: 190 },
      { step: "Compare plans", detail: "Scanned 4 providers", latencyMs: 150 },
      { step: "Apply", detail: "Switched to off-peak tariff", latencyMs: 140 },
      { step: "Report", detail: "Projected $11/mo savings", latencyMs: 60 },
    ],
    payload: { savings: "$11/mo", provider: "Pacific Power" },
  },
];

export const initialIntegrations: IntegrationItem[] = [
  {
    id: "i-1",
    name: "Google Calendar",
    provider: "Google",
    description: "Schedule arbitration, conflict detection, smart booking.",
    connected: true,
    permissions: ["read:events", "write:events"],
    category: "Calendar",
    syncMinutes: 15,
    lastSync: Date.now() - 1000 * 60 * 3,
  },
  {
    id: "i-2",
    name: "Gmail",
    provider: "Google",
    description: "Invoice scanning, receipt parsing, bill detection.",
    connected: true,
    permissions: ["read:inbox"],
    category: "Finance",
    syncMinutes: 10,
    lastSync: Date.now() - 1000 * 60 * 7,
  },
  {
    id: "i-3",
    name: "Chase Bank",
    provider: "Chase",
    description: "Autonomous payments, budget tracking, reconciliation.",
    connected: true,
    permissions: ["read:balance", "transfer:limited"],
    category: "Finance",
    syncMinutes: 30,
    lastSync: Date.now() - 1000 * 60 * 12,
  },
  {
    id: "i-4",
    name: "Pacific Power",
    provider: "Utilities",
    description: "Usage monitoring, tariff optimization, bill review.",
    connected: true,
    permissions: ["read:usage", "write:plan"],
    category: "Finance",
    syncMinutes: 60,
    lastSync: Date.now() - 1000 * 60 * 21,
  },
  {
    id: "i-5",
    name: "Roborock Smart Home",
    provider: "Smart Home",
    description: "Chore dispatch, cleaning schedules, home routines.",
    connected: true,
    permissions: ["write:commands"],
    category: "Errands",
    syncMinutes: 5,
    lastSync: Date.now() - 1000 * 30,
  },
  {
    id: "i-6",
    name: "Instacart",
    provider: "Grocery",
    description: "Recurring grocery orders, price variance detection.",
    connected: true,
    permissions: ["read:orders", "write:modify"],
    category: "Errands",
    syncMinutes: 20,
    lastSync: Date.now() - 1000 * 60 * 34,
  },
];