"""
LangGraph Shared State Schema for LifePilot Control Console.

Defines the state structures passed across Planner, Strands Agents,
and Human-in-the-Loop (HITL) execution nodes.
"""

from typing import Any, Dict, List, Optional, Sequence
from typing_extensions import Annotated, TypedDict
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class PendingAction(TypedDict, total=False):
    """
    Metadata payload representing a high-risk operation requiring human review.
    """
    action_type: str
    description: str
    parameters: Dict[str, Any]
    risk_level: str  # 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
    requested_by_agent: str


class TaskItem(TypedDict, total=False):
    """
    Individual step structure generated by the Planner node.
    """
    id: str
    title: str
    assigned_agent: str
    action_type: str
    description: str
    risk_level: str
    parameters: Dict[str, Any]
    status: str  # 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'FAILED'


class AgentState(TypedDict, total=False):
    """
    Primary LangGraph execution state for LifePilot agent workflows.
    """
    # 1. Message History (Appends incoming messages incrementally)
    messages: Annotated[Sequence[BaseMessage], add_messages]

    # 2. Operational Identifiers & Workspace Metadata
    thread_id: str
    user_id: str
    organization_id: str
    user_goal: str

    # 3. Task Planning & Sequence Progression
    plan_tasks: List[TaskItem]
    current_task_index: int
    current_task: Optional[TaskItem]
    current_agent: str
    planner_notes: Optional[str]

    # 4. Human-in-the-Loop (HITL) Approval Management
    requires_human_approval: bool
    pending_action: Optional[PendingAction]
    is_approved: bool
    approval_status: str  # 'pending' | 'approved' | 'rejected' | 'bypassed'
    approval_feedback: Optional[str]

    # 5. Workflow Execution Control & Output Telemetry
    is_complete: bool
    error: Optional[str]
    execution_results: List[Dict[str, Any]]
    updated_at: str