services:


  backend:

    build:
      context: .
      dockerfile: Dockerfile


    container_name: lifepilot_backend


    restart: unless-stopped


    working_dir: /app


    ports:
      - "8000:8000"


    environment:

      DJANGO_SETTINGS_MODULE: config.settings

      PYTHONPATH: /app


      SECRET_KEY: ${SECRET_KEY:-django-insecure-change-this}

      DEBUG: ${DEBUG:-1}


      ALLOWED_HOSTS: "*"


      DB_ENGINE:
        django.db.backends.postgresql


      DB_NAME:
        lifepilot-control-console


      DB_USER:
        lifepilot-control-consoleadmin


      DB_PASSWORD:
        "000000"


      DB_HOST:
        postgres


      DB_PORT:
        5432


      REDIS_HOST:
        redis


      REDIS_PORT:
        6379


      REDIS_URL:
        redis://redis:6379/0


      USE_IN_MEMORY_CHANNEL_LAYER:
        "0"



    env_file:

      - backend/.env



    depends_on:


      postgres:

        condition: service_healthy


      redis:

        condition: service_healthy



    volumes:

      - ./backend:/app

      - static_volume:/app/staticfiles

      - media_volume:/app/media





  postgres:


    image: postgres:16-alpine


    container_name: lifepilot_postgres


    restart: unless-stopped


    environment:


      POSTGRES_DB:
        lifepilot-control-console


      POSTGRES_USER:
        lifepilot-control-consoleadmin


      POSTGRES_PASSWORD:
        "000000"



    ports:

      - "5432:5432"



    volumes:

      - postgres_data:/var/lib/postgresql/data



    healthcheck:

      test:
        [
          "CMD-SHELL",
          "pg_isready -U lifepilot-control-consoleadmin -d lifepilot-control-console"
        ]

      interval: 5s

      timeout: 5s

      retries: 10





  redis:


    image: redis:7-alpine


    container_name: lifepilot_redis


    restart: unless-stopped



    ports:

      - "6379:6379"



    volumes:

      - redis_data:/data



    healthcheck:

      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]

      interval: 5s

      timeout: 5s

      retries: 10





volumes:

  postgres_data:


  redis_data:


  static_volume:


  media_volume: