# Generated by Django 6.1 on 2026-09-05 22:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active_threads_count', models.IntegerField(default=0)),
                ('pending_approvals_count', models.IntegerField(default=0)),
                ('connected_integrations_count', models.IntegerField(default=0)),
                ('healthy_integrations_count', models.IntegerField(default=0)),
                ('total_executions_24h', models.IntegerField(default=0)),
                ('successful_executions_24h', models.IntegerField(default=0)),
                ('failed_executions_24h', models.IntegerField(default=0)),
                ('success_rate_pct', models.FloatField(default=100.0)),
                ('avg_execution_time_ms', models.FloatField(default=0.0)),
                ('raw_telemetry_data', models.JSONField(blank=True, default=dict, help_text='Detailed JSON dump of aggregated telemetry counters.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(help_text='The user associated with this metric snapshot.', on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Metric Snapshot',
                'verbose_name_plural': 'Dashboard Metric Snapshots',
                'db_table': 'dashboard_metric_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboardPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_refresh_enabled', models.BooleanField(default=True)),
                ('refresh_interval_seconds', models.IntegerField(default=30, help_text='Telemetry auto-refresh interval in seconds (e.g., 5, 15, 30, 60).')),
                ('default_tab', models.CharField(default='overview', help_text="Default view tab on launch (e.g., 'overview', 'approvals', 'integrations').", max_length=50)),
                ('visible_widgets', models.JSONField(blank=True, default=list, help_text='List of enabled widget identifiers on the dashboard view.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Dashboard Preference',
                'verbose_name_plural': 'User Dashboard Preferences',
                'db_table': 'dashboard_user_preferences',
            },
        ),
    ]
