# Generated by Django 6.1 on 2026-09-05 22:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name of the agent.', max_length=255)),
                ('slug', models.SlugField(help_text='Unique identifier for routing.', max_length=255, unique=True)),
                ('track', models.CharField(choices=[('everyday', 'Everyday Agents (Busywork, Home, Health, Errands)'), ('professional', 'Professional Agents (Workplace, Creator, SMB)'), ('good_neighbor', 'Good Neighbor Agents (Community, Local Orgs)')], default='everyday', help_text='Hackathon submission track alignment.', max_length=32)),
                ('description', models.TextField(help_text='Functional scope and background tasks handled by this agent.')),
                ('strands_model', models.CharField(default='gemini-2.5-flash', help_text='Strands SDK model engine (e.g., gemini-2.5-flash, bedrock/anthropic.claude-3-5-sonnet).', max_length=128)),
                ('aws_bedrock_agent_id', models.CharField(blank=True, help_text='AWS Bedrock / AgentCore deployment resource ID for production execution.', max_length=255, null=True)),
                ('aws_agent_alias_id', models.CharField(blank=True, help_text='AWS Bedrock Agent Alias ID for versioned deployment.', max_length=255, null=True)),
                ('system_prompt', models.TextField(help_text="Base system prompt instructions defining the agent's behavior and constraints.")),
                ('max_iterations', models.PositiveIntegerField(default=15, help_text='Maximum autonomous reasoning/tool execution steps permitted per run.')),
                ('requires_hitl', models.BooleanField(default=True, help_text='If True, critical side-effect tools require explicit Human-in-the-Loop approval.')),
                ('is_active', models.BooleanField(default=True, help_text='Soft toggle to enable or pause agent execution.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent Definition',
                'verbose_name_plural': 'Agent Definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField(help_text='Sequential step order in execution graph.')),
                ('step_type', models.CharField(choices=[('reasoning', 'LLM Thought / Reasoning Step'), ('tool_call', 'Tool Execution Call'), ('tool_result', 'Tool Observation Output'), ('langgraph_node', 'LangGraph State Transition'), ('hitl_gate', 'Human Approval Interrupt')], default='reasoning', max_length=32)),
                ('node_name', models.CharField(blank=True, help_text="LangGraph workflow node name (e.g., 'planner', 'strands_runner', 'hitl_checker').", max_length=128, null=True)),
                ('tool_name', models.CharField(blank=True, help_text='Name of the Strands tool invoked during this step.', max_length=128, null=True)),
                ('tool_input', models.JSONField(blank=True, help_text='Arguments passed to the tool function.', null=True)),
                ('tool_output', models.JSONField(blank=True, help_text='Data payload returned by tool execution.', null=True)),
                ('thought_process', models.TextField(blank=True, help_text='Agent internal monologue / reasoning behind this action.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agent Execution Step',
                'verbose_name_plural': 'Agent Execution Steps',
                'ordering': ['run', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='HumanApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(help_text="Action requiring human authorization (e.g., 'send_email', 'pay_bill', 'delete_file').", max_length=128)),
                ('action_description', models.TextField(help_text='Human-readable explanation of why approval is required and what will happen.')),
                ('proposed_payload', models.JSONField(default=dict, help_text='The precise parameters and payload the agent plans to execute if approved.')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('pending', 'Pending Queue'), ('running', 'Autonomous Execution Running'), ('awaiting_approval', 'Awaiting Human Approval (HITL)'), ('approved', 'Approval Granted'), ('rejected', 'Approval Rejected'), ('completed', 'Completed Successfully'), ('failed', 'Execution Failed'), ('cancelled', 'Execution Cancelled')], db_index=True, default='awaiting_approval', max_length=32)),
                ('rejection_reason', models.TextField(blank=True, help_text='Optional notes provided by user upon rejection.', null=True)),
                ('expires_at', models.DateTimeField(help_text='Expiration timestamp after which the approval request automatically times out.')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Human Approval Request',
                'verbose_name_plural': 'Human Approval Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thread_id', models.CharField(db_index=True, help_text='LangGraph checkpointer thread ID for persistent state recovery.', max_length=255)),
                ('checkpoint_ns', models.CharField(blank=True, default='', help_text='LangGraph state namespace.', max_length=255)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('pending', 'Pending Queue'), ('running', 'Autonomous Execution Running'), ('awaiting_approval', 'Awaiting Human Approval (HITL)'), ('approved', 'Approval Granted'), ('rejected', 'Approval Rejected'), ('completed', 'Completed Successfully'), ('failed', 'Execution Failed'), ('cancelled', 'Execution Cancelled')], db_index=True, default='pending', max_length=32)),
                ('input_payload', models.JSONField(default=dict, help_text='Initial task payload, user preferences, and trigger parameters.')),
                ('output_result', models.JSONField(blank=True, default=dict, help_text='Final structured output returned by the Strands Agent execution.')),
                ('error_message', models.TextField(blank=True, help_text='Detailed error stack trace if execution fails.', null=True)),
                ('tokens_used', models.PositiveIntegerField(default=0, help_text='Total LLM token usage across run steps.')),
                ('execution_time_seconds', models.FloatField(default=0.0, help_text='Total duration of agent execution.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(help_text='Parent agent definition.', on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='agents.agentdefinition')),
            ],
            options={
                'verbose_name': 'Agent Execution Run',
                'verbose_name_plural': 'Agent Execution Runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
