# Generated by Django 6.1 on 2026-09-05 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='user',
            field=models.ForeignKey(help_text='User on whose behalf the autonomous agent operates.', on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentstep',
            name='run',
            field=models.ForeignKey(help_text='Associated agent execution run.', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agents.agentrun'),
        ),
        migrations.AddField(
            model_name='humanapprovalrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='User who approved or rejected the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='humanapprovalrequest',
            name='run',
            field=models.ForeignKey(help_text='Agent run currently paused awaiting human judgment.', on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='agents.agentrun'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['thread_id', 'status'], name='agents_agen_thread__18b8d7_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['user', 'status'], name='agents_agen_user_id_f3c82e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentstep',
            unique_together={('run', 'step_number')},
        ),
    ]
