# Generated by Django 6.1 on 2026-09-05 22:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the approval request.', primary_key=True, serialize=False)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk (Read-only / Safe operations)'), ('medium', 'Medium Risk (Modifying benign non-critical resources)'), ('high', 'High Risk (Production system modifications, high financial cost)'), ('critical', 'Critical Risk (Data deletion, security credential rotations, core infrastructure changes)')], db_index=True, default='high', help_text='Evaluated risk level of the pending action.', max_length=20)),
                ('action_type', models.CharField(db_index=True, help_text="Identifier of the operation (e.g., 'aws:terminate_instance', 'db:drop_table', 'email:send_bulk').", max_length=100)),
                ('action_description', models.TextField(help_text='Human-readable explanation generated by the agent detailing what it intends to do and why.')),
                ('proposed_payload', models.JSONField(default=dict, help_text='Structured arguments and parameters the agent intends to pass to the tool/AWS API.')),
                ('thread_id', models.CharField(blank=True, help_text='LangGraph thread ID associated with the paused state graph.', max_length=255, null=True)),
                ('checkpoint_ns', models.CharField(blank=True, default='', help_text='LangGraph checkpointer namespace where the workflow state is suspended.', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Human Review'), ('approved', 'Approved by User'), ('rejected', 'Rejected by User'), ('expired', 'Timed Out / Auto-Expired'), ('cancelled', 'Cancelled by Agent Workflow')], db_index=True, default='pending', help_text='Current state of the authorization request.', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='User-provided context or explanation if the action was rejected.')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Expiration threshold after which the request automatically transitions to EXPIRED.', null=True)),
                ('decided_at', models.DateTimeField(blank=True, help_text='Timestamp when the human reviewer submitted their decision.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the approval request was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Requests',
                'db_table': 'approvals_approval_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_taken', models.CharField(max_length=50)),
                ('payload_snapshot', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Approval Audit Log',
                'verbose_name_plural': 'Approval Audit Logs',
                'db_table': 'approvals_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
