# Generated by Django 6.1 on 2026-09-05 22:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text="Unique identifier slug (e.g., 'google-calendar', 'slack', 'github').", unique=True)),
                ('name', models.CharField(help_text='Display name of the integration provider.', max_length=100)),
                ('category', models.CharField(choices=[('COMMUNICATION', 'Communication & Messaging'), ('CALENDAR', 'Calendar & Scheduling'), ('PRODUCTIVITY', 'Productivity & Workspace'), ('DEVELOPMENT', 'Development & DevOps'), ('INFRASTRUCTURE', 'Cloud & Infrastructure')], default='PRODUCTIVITY', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Short description of tool capabilities.')),
                ('icon_url', models.URLField(blank=True, help_text='URL or path to service icon asset.', null=True)),
                ('auth_type', models.CharField(choices=[('OAUTH2', 'OAuth 2.0'), ('API_KEY', 'API Key / Token'), ('WEBHOOK', 'Webhook Secret')], default='OAUTH2', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether this integration is selectable by users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration Provider',
                'verbose_name_plural': 'Integration Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConnectedIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected & Active'), ('DISCONNECTED', 'Disconnected'), ('EXPIRED', 'Credentials Expired'), ('ERROR', 'Configuration Error'), ('PENDING_OAUTH', 'Pending OAuth Authorization')], default='PENDING_OAUTH', max_length=20)),
                ('account_identifier', models.CharField(blank=True, help_text="External account identifier (e.g., 'user@gmail.com' or Slack workspace ID).", max_length=255)),
                ('access_token', models.TextField(blank=True, help_text='OAuth access token or API key.', null=True)),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token if applicable.', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_scopes', models.JSONField(blank=True, default=list, help_text='List of OAuth permissions/scopes authorized by the user.')),
                ('config_payload', models.JSONField(blank=True, default=dict, help_text='Service-specific configurations (e.g., default channels, sync intervals).')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of the connected integration.', on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections', to='integrations.integrationprovider')),
            ],
            options={
                'verbose_name': 'Connected Integration',
                'verbose_name_plural': 'Connected Integrations',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'provider', 'account_identifier')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text="Event type received (e.g., 'calendar.event_updated').", max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('processed_successfully', models.BooleanField(default=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='integrations.connectedintegration')),
            ],
            options={
                'verbose_name': 'Integration Webhook Log',
                'verbose_name_plural': 'Integration Webhook Logs',
                'ordering': ['-received_at'],
            },
        ),
    ]
