"""
Data models for Human-in-the-Loop (HITL) Workflows & Approval Gates.

Aligned with the Agents for Humans Hackathon requirements:
- Intercepts sensitive/destructive action proposals generated by Strands SDK agents & LangGraph nodes.
- Provides complete audit trailing for human decisions (Approval, Rejection, Expiration).
- Serves as the persistence layer for AWS Bedrock / AgentCore HITL policies.
"""

import uuid
from django.conf import settings
from django.db import models
from django.utils import timezone


class ActionRiskLevel(models.TextChoices):
    """Categorizes the blast radius and potential risk of an agent's proposed operation."""
    LOW = "low", "Low Risk (Read-only / Safe operations)"
    MEDIUM = "medium", "Medium Risk (Modifying benign non-critical resources)"
    HIGH = "high", "High Risk (Production system modifications, high financial cost)"
    CRITICAL = "critical", "Critical Risk (Data deletion, security credential rotations, core infrastructure changes)"


class ApprovalStatus(models.TextChoices):
    """Lifecycle states for a Human-in-the-Loop request."""
    PENDING = "pending", "Pending Human Review"
    APPROVED = "approved", "Approved by User"
    REJECTED = "rejected", "Rejected by User"
    EXPIRED = "expired", "Timed Out / Auto-Expired"
    CANCELLED = "cancelled", "Cancelled by Agent Workflow"


class ApprovalRequest(models.Model):
    """
    Tracks a single Human-in-the-Loop (HITL) authorization request.

    When an agent (via Strands SDK or a LangGraph human_approval node) encounters an action 
    that requires verification, execution pauses, a state checkpoint is created, and an instance 
    of this model is populated to await human intervention.
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text="Unique identifier for the approval request.",
    )

    # Relationship to the agent run initiating this request
    # Uses string reference to avoid circular dependencies with apps.agents
    run = models.ForeignKey(
        "agents.AgentRun",
        on_delete=models.CASCADE,
        related_name="approvals",
        help_text="The agent execution run that requested authorization.",
    )

    # Risk assessment
    risk_level = models.CharField(
        max_length=20,
        choices=ActionRiskLevel.choices,
        default=ActionRiskLevel.HIGH,
        db_index=True,
        help_text="Evaluated risk level of the pending action.",
    )

    # Action metadata
    action_type = models.CharField(
        max_length=100,
        db_index=True,
        help_text="Identifier of the operation (e.g., 'aws:terminate_instance', 'db:drop_table', 'email:send_bulk').",
    )

    action_description = models.TextField(
        help_text="Human-readable explanation generated by the agent detailing what it intends to do and why.",
    )

    proposed_payload = models.JSONField(
        default=dict,
        help_text="Structured arguments and parameters the agent intends to pass to the tool/AWS API.",
    )

    # LangGraph state checkpoint tracking
    thread_id = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        help_text="LangGraph thread ID associated with the paused state graph.",
    )

    checkpoint_ns = models.CharField(
        max_length=255,
        blank=True,
        default="",
        help_text="LangGraph checkpointer namespace where the workflow state is suspended.",
    )

    # Status tracking
    status = models.CharField(
        max_length=20,
        choices=ApprovalStatus.choices,
        default=ApprovalStatus.PENDING,
        db_index=True,
        help_text="Current state of the authorization request.",
    )

    # User decision audit trail
    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="approval_requests_reviewed",
        help_text="The user who approved or rejected the request.",
    )

    rejection_reason = models.TextField(
        blank=True,
        default="",
        help_text="User-provided context or explanation if the action was rejected.",
    )

    # Timestamps & Time-to-Live (TTL)
    expires_at = models.DateTimeField(
        blank=True,
        null=True,
        db_index=True,
        help_text="Expiration threshold after which the request automatically transitions to EXPIRED.",
    )

    decided_at = models.DateTimeField(
        blank=True,
        null=True,
        help_text="Timestamp when the human reviewer submitted their decision.",
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        help_text="Timestamp when the approval request was created.",
    )

    updated_at = models.DateTimeField(
        auto_now=True,
        help_text="Timestamp when the record was last modified.",
    )

    class Meta:
        db_table = "approvals_approval_request"
        ordering = ["-created_at"]
        verbose_name = "Approval Request"
        verbose_name_plural = "Approval Requests"
        indexes = [
            models.Index(fields=["status", "created_at"]),
            models.Index(fields=["run", "status"]),
        ]

    def __str__(self) -> str:
        return f"ApprovalRequest[{self.action_type}] ({self.get_status_display()}) - Run {self.run_id}"

    @property
    def is_expired(self) -> bool:
        """Checks if the request has surpassed its validity window."""
        if self.expires_at and timezone.now() >= self.expires_at:
            return True
        return False

    def approve(self, user) -> None:
        """Helper to mark request as approved by a human reviewer."""
        if self.status != ApprovalStatus.PENDING:
            raise ValueError(f"Cannot approve request in '{self.status}' state.")
        
        self.status = ApprovalStatus.APPROVED
        self.reviewed_by = user
        self.decided_at = timezone.now()
        self.save(update_fields=["status", "reviewed_by", "decided_at", "updated_at"])

    def reject(self, user, reason: str = "") -> None:
        """Helper to mark request as rejected by a human reviewer."""
        if self.status != ApprovalStatus.PENDING:
            raise ValueError(f"Cannot reject request in '{self.status}' state.")

        self.status = ApprovalStatus.REJECTED
        self.reviewed_by = user
        self.rejection_reason = reason
        self.decided_at = timezone.now()
        self.save(update_fields=["status", "reviewed_by", "rejection_reason", "decided_at", "updated_at"])


class AuditLog(models.Model):
    """
    Immutable ledger of all approval request decisions for compliance and auditing.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    approval_request = models.ForeignKey(
        ApprovalRequest,
        on_delete=models.CASCADE,
        related_name="audit_logs",
    )
    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    action_taken = models.CharField(max_length=50)  # e.g., 'APPROVED', 'REJECTED', 'EXPIRED'
    payload_snapshot = models.JSONField(default=dict)
    notes = models.TextField(blank=True, default="")
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        db_table = "approvals_audit_log"
        ordering = ["-timestamp"]
        verbose_name = "Approval Audit Log"
        verbose_name_plural = "Approval Audit Logs"

    def __str__(self) -> str:
        return f"AuditLog[{self.action_taken}] for Approval {self.approval_request_id} at {self.timestamp}"