"""
Django REST Framework Serializers for LifePilot Human-in-the-Loop (HITL) Approvals.

Aligned with the Agents for Humans Hackathon requirements:
- Handles HITL authorization requests generated by Strands SDK & LangGraph workflows.
- Validates approval/rejection decision actions submitted by human reviewers.
- Serializes audit logs for compliance tracking across AWS Bedrock / AgentCore environments.
"""

from rest_framework import serializers
from django.utils import timezone
from apps.approvals.models import ActionRiskLevel, ApprovalRequest, ApprovalStatus, AuditLog


class AuditLogSerializer(serializers.ModelSerializer):
    """Serializer for immutable approval audit log records."""

    actor_email = serializers.EmailField(source="actor.email", read_only=True, default=None)

    class Meta:
        model = AuditLog
        fields = [
            "id",
            "approval_request",
            "actor",
            "actor_email",
            "action_taken",
            "payload_snapshot",
            "notes",
            "timestamp",
        ]
        read_only_fields = fields


class ApprovalRequestSerializer(serializers.ModelSerializer):
    """
    Serializer for reviewing and inspecting Human-in-the-Loop (HITL) authorization requests.
    """

    status_display = serializers.CharField(source="get_status_display", read_only=True)
    risk_level_display = serializers.CharField(source="get_risk_level_display", read_only=True)
    reviewed_by_email = serializers.EmailField(source="reviewed_by.email", read_only=True, default=None)
    is_expired = serializers.BooleanField(read_only=True)
    audit_logs = AuditLogSerializer(many=True, read_only=True)

    class Meta:
        model = ApprovalRequest
        fields = [
            "id",
            "run",
            "risk_level",
            "risk_level_display",
            "action_type",
            "action_description",
            "proposed_payload",
            "thread_id",
            "checkpoint_ns",
            "status",
            "status_display",
            "reviewed_by",
            "reviewed_by_email",
            "rejection_reason",
            "expires_at",
            "is_expired",
            "decided_at",
            "created_at",
            "updated_at",
            "audit_logs",
        ]
        read_only_fields = [
            "id",
            "run",
            "risk_level",
            "action_type",
            "action_description",
            "proposed_payload",
            "thread_id",
            "checkpoint_ns",
            "status",
            "reviewed_by",
            "rejection_reason",
            "expires_at",
            "decided_at",
            "created_at",
            "updated_at",
            "audit_logs",
        ]


class ApprovalDecisionActionSerializer(serializers.Serializer):
    """
    Serializer for validating incoming user decision payloads (Approve / Reject).
    """

    decision = serializers.ChoiceField(
        choices=[(ApprovalStatus.APPROVED, "Approve"), (ApprovalStatus.REJECTED, "Reject")],
        required=True,
        help_text="The decision to apply: 'approved' or 'rejected'.",
    )
    notes = serializers.CharField(
        required=False,
        allow_blank=True,
        default="",
        help_text="Optional feedback or rejection reason explaining the decision.",
    )

    def validate(self, data):
        """Ensure rejection includes a reason when applicable."""
        decision = data.get("decision")
        notes = data.get("notes", "").strip()

        if decision == ApprovalStatus.REJECTED and not notes:
            # Rejection notes are strongly encouraged for audit clarity
            data["notes"] = "Rejected by reviewer without explicit reason."

        return data


class ApprovalRequestCreateSerializer(serializers.ModelSerializer):
    """
    Serializer used internally by Strands SDK / LangGraph nodes to register new HITL checkpoints.
    """

    class Meta:
        model = ApprovalRequest
        fields = [
            "run",
            "risk_level",
            "action_type",
            "action_description",
            "proposed_payload",
            "thread_id",
            "checkpoint_ns",
            "expires_at",
        ]

    def validate_risk_level(self, value):
        if value not in ActionRiskLevel.values:
            raise serializers.ValidationError(f"Invalid risk level '{value}'.")
        return value