"""
API Views for LifePilot Human-in-the-Loop (HITL) Approvals Management.

Aligned with project requirements:
- Inspect pending and historical HITL approval requests generated by Strands SDK / LangGraph runs.
- Submit human authorization decisions (Approve / Reject) and trigger workflow resumption via services.
- Retrieve immutable audit logs for security, compliance, and AWS Bedrock / AgentCore auditing.
"""

import logging
from django.db import transaction
from django.utils import timezone
from rest_framework import filters, status, viewsets
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.request import Request
from rest_framework.response import Response

from django_filters.rest_framework import DjangoFilterBackend

from apps.approvals.models import ApprovalRequest, ApprovalStatus, AuditLog
from apps.approvals.serializers import (
    ApprovalDecisionActionSerializer,
    ApprovalRequestSerializer,
    AuditLogSerializer,
)
from apps.approvals.services import resume_agent_workflow

logger = logging.getLogger("lifepilot.approvals.views")


class ApprovalRequestViewSet(viewsets.ReadOnlyModelViewSet):
    """
    ViewSet for inspecting and resolving Human-in-the-Loop (HITL) approval requests.
    """

    queryset = (
        ApprovalRequest.objects.select_related("run", "reviewed_by")
        .prefetch_related("audit_logs")
        .all()
    )
    serializer_class = ApprovalRequestSerializer
    permission_classes = [IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ["status", "risk_level", "action_type", "run"]
    search_fields = ["action_type", "action_description", "run__id"]
    ordering_fields = ["created_at", "decided_at", "expires_at", "risk_level"]
    ordering = ["-created_at"]

    def get_queryset(self):
        """Scope approval requests to the authenticated user's agent runs."""
        return self.queryset.filter(run__user=self.request.user)

    @action(detail=True, methods=["post"], url_path="decision")
    def submit_decision(self, request: Request, pk: str = None) -> Response:
        """
        Submit a human decision ('approved' or 'rejected') for a pending HITL authorization request.
        
        Applies state updates, records an immutable AuditLog, and triggers workflow resumption
        for suspended LangGraph / Strands execution threads.
        """
        approval_request = self.get_object()

        # 1. Check if already resolved
        if approval_request.status != ApprovalStatus.PENDING:
            return Response(
                {
                    "detail": f"Approval request '{approval_request.id}' is already resolved with status '{approval_request.status}'."
                },
                status=status.HTTP_400_BAD_REQUEST,
            )

        # 2. Check for expiration
        if approval_request.is_expired:
            approval_request.status = ApprovalStatus.EXPIRED
            approval_request.save(update_fields=["status", "updated_at"])
            return Response(
                {"detail": f"Approval request '{approval_request.id}' has expired and cannot be acted upon."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        # 3. Validate decision payload
        serializer = ApprovalDecisionActionSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        decision = serializer.validated_data["decision"]
        notes = serializer.validated_data.get("notes", "")

        # 4. Atomic database state update & audit logging
        with transaction.atomic():
            if decision == ApprovalStatus.APPROVED:
                approval_request.approve(user=request.user)
            else:
                approval_request.reject(user=request.user, reason=notes)

            # Record immutable compliance log entry
            AuditLog.objects.create(
                approval_request=approval_request,
                actor=request.user,
                action_taken=approval_request.status.upper(),
                payload_snapshot=approval_request.proposed_payload,
                notes=notes,
            )

            # Update associated agent run status
            agent_run = approval_request.run
            if decision == ApprovalStatus.APPROVED:
                agent_run.status = "running"
            else:
                agent_run.status = "failed"
                agent_run.error_message = f"Action rejected during HITL review: {notes or 'No reason provided.'}"
                agent_run.completed_at = timezone.now()

            agent_run.save(update_fields=["status", "error_message", "completed_at", "updated_at"])

        logger.info(
            "HITL request [%s] marked as %s by user [%s]",
            approval_request.id,
            approval_request.status,
            request.user.id,
        )

        # 5. Resume execution thread via service layer
        resumption_details = None
        try:
            resumption_details = resume_agent_workflow(approval_request=approval_request)
        except Exception as exc:
            logger.error(
                "Failed to trigger workflow resumption for ApprovalRequest [%s]: %s",
                approval_request.id,
                exc,
            )

        response_serializer = ApprovalRequestSerializer(approval_request)
        return Response(
            {
                "message": f"HITL decision '{decision}' applied successfully.",
                "approval": response_serializer.data,
                "resumption": resumption_details,
            },
            status=status.HTTP_200_OK,
        )

    @action(detail=False, methods=["get"], url_path="pending-count")
    def pending_count(self, request: Request) -> Response:
        """Returns total count of pending HITL approvals requiring human review."""
        count = self.get_queryset().filter(status=ApprovalStatus.PENDING).count()
        return Response({"pending_count": count}, status=status.HTTP_200_OK)


class AuditLogViewSet(viewsets.ReadOnlyModelViewSet):
    """
    ReadOnly API ViewSet for inspecting immutable HITL decision audit logs.
    """

    queryset = AuditLog.objects.select_related("approval_request", "actor").all()
    serializer_class = AuditLogSerializer
    permission_classes = [IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.OrderingFilter]
    filterset_fields = ["action_taken", "approval_request"]
    ordering_fields = ["timestamp"]
    ordering = ["-timestamp"]

    def get_queryset(self):
        return self.queryset.filter(approval_request__run__user=self.request.user)
